# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP URL')),
                ('user_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request User')),
                ('method_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Method Type')),
                ('method_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Name')),
                ('request_content', models.TextField(blank=True, null=True, verbose_name='Request Parameter')),
                ('request_length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request Size in KB')),
                ('response_status_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Response Status')),
                ('response_content', models.TextField(blank=True, null=True, verbose_name='Response Content')),
                ('response_length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Response Size in KB')),
                ('time_taken', models.FloatField(blank=True, null=True, verbose_name='Response Time')),
                ('extra_log', models.TextField(blank=True, null=True, verbose_name='Extra Log')),
                ('exception_full_stack_trace', models.TextField(blank=True, null=True)),
                ('exception_short_value', models.CharField(blank=True, max_length=255, null=True)),
                ('request_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
