# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Juntos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuntosAboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='About subject')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='JuntosCareers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heading')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Juntos Careers',
            },
        ),
        migrations.CreateModel(
            name='JuntosContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to='Juntos.MyUser')),
            ],
            options={
                'verbose_name_plural': 'List of Contacted Customer',
            },
        ),
        migrations.CreateModel(
            name='JuntosFAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_matter', models.CharField(max_length=200, verbose_name='FAQs subject')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('asked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_user', to='Juntos.MyUser')),
            ],
            options={
                'verbose_name_plural': 'List of FAQs',
            },
        ),
        migrations.CreateModel(
            name='JuntosTermCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heading')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Juntos Terms and Conditions',
            },
        ),
    ]
