# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static_Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juntoscontactusemail',
            name='contactemail',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email Address'),
        ),
    ]
