# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Static_Model', '0002_auto_20171215_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuntosContactUsEmail',
        ),
    ]
