# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static_Model', '0002_delete_juntoscontactusemail'),
    ]

    operations = [
    ]
