# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Static_Model', '0003_juntoscontactusemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuntosContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactemail', models.EmailField(max_length=50, null=True, verbose_name='Email Address')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject')),
                ('message', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Details',
            },
        ),
    ]
