# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Static_Model', '0005_delete_juntoscontactusemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuntosAboutus',
        ),
        migrations.DeleteModel(
            name='JuntosCareers',
        ),
        migrations.RemoveField(
            model_name='juntoscontactus',
            name='contact_user',
        ),
        migrations.RemoveField(
            model_name='juntosfaqs',
            name='asked_user',
        ),
        migrations.DeleteModel(
            name='JuntosTermCondition',
        ),
        migrations.DeleteModel(
            name='SubscribeNewsLetter',
        ),
        migrations.DeleteModel(
            name='JuntosContactUs',
        ),
        migrations.DeleteModel(
            name='JuntosFAQs',
        ),
    ]
