# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 06:43
from __future__ import unicode_literals

import autoslug.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Juntos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('priority', models.IntegerField(blank=True, default=1, null=True)),
                ('Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Category icon')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_tag', models.CharField(choices=[[None, 'Select tag'], ['SP', 'Simple Product'], ['CP', 'Configurable product'], ['VP', 'Virtual Product'], ['DP', 'Downloadable Product'], ['GP', 'Grouped Product'], ['BP', 'Bundled Product']], max_length=120, verbose_name='Subcategory tag')),
                ('sub_category_name', models.CharField(max_length=120, verbose_name='Sub category name')),
                ('priority', models.IntegerField(blank=True, default=1, null=True)),
                ('subcategory_size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['1', 'Extra Small'], ['2', 'Small'], ['3', 'Medium'], ['4', 'Large'], ['5', 'Extra Large']], default='', max_length=50, null=True)),
                ('subcategory_shoes_size', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['9', '9'], ['10', '10'], ['11', '11']], default='', max_length=50, null=True)),
                ('sub_category_flage', models.CharField(blank=True, choices=[[None, 'Select Flage'], ['CLOTH', 'Clothes'], ['SHOES', 'Shoes or Boots']], help_text='Is Cloth or Shoes ?', max_length=10, null=True, verbose_name='Sub Category Flage')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='sub_category_name', unique_with=('sub_category_name',))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='Juntos.Category')),
            ],
            options={
                'verbose_name_plural': 'Product Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
