# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0003_auto_20170925_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_tag',
            field=models.CharField(blank=True, choices=[[None, 'Select tag'], ['SP', 'Simple Product'], ['CP', 'Configurable product'], ['VP', 'Virtual Product'], ['DP', 'Downloadable Product'], ['GP', 'Grouped Product'], ['BP', 'Bundled Product']], default='CP', max_length=120, null=True, verbose_name='Subcategory tag'),
        ),
    ]
