# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 07:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0004_auto_20170925_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='sub_category_name', unique_with=('sub_category_name',)),
        ),
    ]
