# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 08:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0007_auto_20170925_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['sub_category_name', 'sub_category_tag'], unique=True),
        ),
    ]
