# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 09:27
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0008_auto_20170925_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(blank=True, max_length=50, verbose_name='Product ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product Title')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('feature', models.TextField(blank=True, default='Not a feature product', null=True, verbose_name='Product Features')),
                ('price', models.FloatField(verbose_name='Product Orignal Price')),
                ('selling_price', models.FloatField(verbose_name='Product Selling Price')),
                ('product_quantity', models.IntegerField(verbose_name='Product Available Quantity')),
                ('product_rating', models.IntegerField(default=0, verbose_name='Product Rating')),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='', verbose_name='Product image'), blank=True, null=True, size=None)),
                ('product_tag', models.CharField(blank=True, max_length=300, verbose_name='Product Tag')),
                ('recommended', models.BooleanField(default=False, verbose_name='Mark as Recommended')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='subs_category', unique_with=('title',))),
                ('in_stock', models.BooleanField(default=True, verbose_name='Available')),
                ('insured_amount', models.FloatField(blank=True, null=True, verbose_name='Insured Amount')),
                ('product_weight', models.FloatField(blank=True, null=True, verbose_name='Product Weight')),
                ('product_height', models.FloatField(blank=True, null=True, verbose_name='product_height')),
                ('product_depth', models.FloatField(blank=True, null=True, verbose_name='Product depth')),
                ('product_width', models.FloatField(blank=True, null=True, verbose_name='Product Width')),
                ('expire_products', models.IntegerField(blank=True, default=15, verbose_name='Expired Products')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_product', to='Juntos.Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
        migrations.AddField(
            model_name='productsmanagement',
            name='subs_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat_product', to='Juntos.SubCategory'),
        ),
        migrations.AddField(
            model_name='productsmanagement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendore_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
