# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0010_auto_20170925_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(blank=True, choices=[[1, 'New Order Recived'], [2, 'Order Cancel'], [3, 'Others']], max_length=200, verbose_name='Notification Type')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='Notification content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read ?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nofify_vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
