# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0011_auto_20170926_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Product Rating'),
        ),
    ]
