# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 08:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0013_auto_20170926_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='', verbose_name='Product image'), null=True, size=None),
        ),
    ]
