# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0016_auto_20170927_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='insured_amount',
            field=models.FloatField(verbose_name='Insured Amount'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_depth',
            field=models.FloatField(verbose_name='Product depth'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_height',
            field=models.FloatField(verbose_name='product_height'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_weight',
            field=models.FloatField(verbose_name='Product Weight'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_width',
            field=models.FloatField(verbose_name='Product Width'),
        ),
    ]
