# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0018_productsmanagement_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmanagement',
            name='services',
            field=models.TextField(default='', verbose_name='Services'),
        ),
    ]
