# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 13:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0019_productsmanagement_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='payment_mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Payment Mode'), size=None),
        ),
    ]
