# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0020_auto_20170928_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='selling_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Selling Price'),
        ),
    ]
