# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0026_shipping_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping_Address',
            new_name='ShippingAddress',
        ),
    ]
