# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0028_auto_20171005_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='selected',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='billing_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Billing Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='billing_address',
            field=models.CharField(default='', max_length=500, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address',
            field=models.CharField(default='', max_length=500, verbose_name='Shipping Address'),
        ),
    ]
