# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0030_auto_20171010_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_first_name', models.CharField(max_length=50, verbose_name='Billing First Name')),
                ('billing_last_name', models.CharField(max_length=50, verbose_name='Billing Last Name')),
                ('billing_phone', models.CharField(max_length=15, verbose_name='Billing Phone')),
                ('billing_company', models.CharField(max_length=50, verbose_name='Billing Company')),
                ('billing_country', models.CharField(max_length=50, verbose_name='Billing Country')),
                ('billing_country_abbreviation', models.CharField(max_length=5, verbose_name='Billing Country Abbreviation')),
                ('billing_state', models.CharField(max_length=50, verbose_name='Billing State')),
                ('billing_city', models.CharField(max_length=50, verbose_name='Billing City')),
                ('billing_zip', models.CharField(max_length=50, verbose_name='Billing Zip')),
                ('billing_address', models.CharField(max_length=500, verbose_name='Billing Address')),
                ('billing_email', models.CharField(max_length=50, verbose_name='Billing Email')),
                ('mode_of_transport', models.CharField(max_length=50, verbose_name='Mode of Transport')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_first_name', models.CharField(max_length=50, verbose_name='Shipping First Name')),
                ('shipping_last_name', models.CharField(max_length=50, verbose_name='Shipping Last Name')),
                ('shipping_phone', models.CharField(max_length=15, verbose_name='Shipping Phone')),
                ('shipping_company', models.CharField(max_length=50, verbose_name='Shipping Company')),
                ('shipping_country', models.CharField(max_length=50, verbose_name='Shipping Country')),
                ('shipping_country_abbreviation', models.CharField(max_length=5, verbose_name='Shipping Country Abbreviation')),
                ('shipping_state', models.CharField(max_length=50, verbose_name='Shipping State')),
                ('shipping_city', models.CharField(max_length=50, verbose_name='Shipping City')),
                ('shipping_zip', models.CharField(max_length=50, verbose_name='Shipping Zip')),
                ('shipping_address', models.CharField(max_length=500, verbose_name='Shipping Address')),
                ('shipping_email', models.CharField(max_length=50, verbose_name='Shipping Email')),
                ('mode_of_transport', models.CharField(max_length=50, verbose_name='Mode of Transport')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shiping_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Shipping Address',
            },
        ),
    ]
