# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0031_billingaddress_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='billing_country_abbreviation',
            field=models.CharField(max_length=20, verbose_name='Billing Country Abbreviation'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country_abbreviation',
            field=models.CharField(max_length=20, verbose_name='Shipping Country Abbreviation'),
        ),
    ]
