# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0032_auto_20171011_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Order Number'),
        ),
    ]
