# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0033_orderitems_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmanagement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Product'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Product Rating'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_flage',
            field=models.CharField(blank=True, choices=[[None, 'Select Flage'], ['CLOTH', 'Clothes'], ['SHOES', 'Shoes or Boots']], help_text='Is Cloth or Shoes ?', max_length=10, null=True, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_tag',
            field=models.CharField(blank=True, choices=[[None, 'Select tag'], ['SP', 'Simple'], ['CP', 'Configurable'], ['VP', 'Virtual'], ['DP', 'Downloadable'], ['GP', 'Grouped'], ['BP', 'Bundled']], default='CP', max_length=120, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_shoes_size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['9', '9'], ['10', '10'], ['11', '11']], default='', max_length=50, null=True, verbose_name='Shoes Size'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['1', 'XS'], ['2', 'S'], ['3', 'M'], ['4', 'L'], ['5', 'XL']], default='', max_length=50, null=True, verbose_name='Size'),
        ),
    ]
