# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0036_auto_20171030_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_image',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_quantity',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_end_date_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_start_date_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OfferProduct', to='Juntos.ProductsManagement'),
        ),
    ]
