# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0037_auto_20171102_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Services')),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_end_date_time',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_start_date_time',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
