# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 06:46
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0038_auto_20171104_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Advertiser Name')),
                ('email', models.CharField(max_length=80, verbose_name='Advertiser Email')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='Advertiser Mobile')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Advertisement Description')),
                ('recommended', models.BooleanField(default=False, verbose_name='Mark as recommended')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price')),
                ('image', models.ImageField(max_length=5000, upload_to='', verbose_name='Advertisement Image')),
                ('new', models.BooleanField(default=True, verbose_name='Mark as new')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='subs_category', unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('subs_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_advertisements', to='Juntos.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'Advertisement',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Type of Services'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='type_of_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Juntos.Services'),
        ),
    ]
