# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 06:50
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0039_auto_20171104_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('advertisement_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_all_images', to='Juntos.Advertisement')),
            ],
            options={
                'verbose_name_plural': 'Manage Advertisement Image',
            },
        ),
    ]
