# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0042_productcolor_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_colr',
            new_name='product_color',
        ),
    ]
