# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0043_auto_20171115_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('case_on_delivery', models.BooleanField(default=False, verbose_name='COD payment option')),
                ('online_payment', models.BooleanField(default=False, verbose_name='Online payment(cerdit card/ debit card/ visa card) option')),
                ('paypal', models.BooleanField(default=False, verbose_name='Paypal payment option')),
                ('services', models.TextField(verbose_name='Delivery services')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payment_method', serialize=False, to='Juntos.ProductsManagement')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
