# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 06:17
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0046_advertisementimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Advertisement Image'),
        ),
    ]
