# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 06:41
from __future__ import unicode_literals

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0047_auto_20171117_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'), size=None),
        ),
    ]
