# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0050_auto_20171117_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
    ]
