# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0052_auto_20171122_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(verbose_name='Tax Percentage')),
            ],
        ),
    ]
