# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0054_customerorderinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_key', models.CharField(blank=True, max_length=100, verbose_name='Order Pay Key')),
                ('payment_status', models.CharField(blank=True, max_length=100, verbose_name='Order Payment Status')),
                ('tranaction_status', models.CharField(blank=True, max_length=50, verbose_name='Transaction Status')),
                ('tranaction_id', models.CharField(blank=True, max_length=50, verbose_name='Transaction ID')),
                ('payment_refunded', models.BooleanField(default=False, verbose_name='Is payment refunded ?')),
                ('payment_refunded_ammount', models.CharField(blank=True, max_length=100, verbose_name='Payment refunded ammount')),
                ('sender_email', models.CharField(blank=True, max_length=100, verbose_name='Payment sender email')),
                ('sender_account_id', models.CharField(blank=True, max_length=100, verbose_name='Payment sender paypal account id')),
                ('reciever_account_id', models.CharField(blank=True, max_length=100, verbose_name='Receiver/Vendor paypal account ID')),
                ('reciever_email', models.CharField(blank=True, max_length=100, verbose_name='Receiver/Vendor paypal account email')),
                ('reciever_amount', models.FloatField(blank=True, default=0.0, verbose_name='Receiver/Vendor paypal account email')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='shipping_percent',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Shipping Percent'),
        ),
        migrations.AddField(
            model_name='customertransactiondetails',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='Juntos.CustomerOrder'),
        ),
    ]
