# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 08:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0055_auto_20171124_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.RemoveField(
            model_name='productsmanagement',
            name='expire_products',
        ),
        migrations.AddField(
            model_name='productsmanagement',
            name='expiry_date',
            field=models.DateField(auto_now=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='', verbose_name='image'), null=True, size=None),
        ),
    ]
