# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0056_auto_20171128_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
    ]
