# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0057_auto_20171128_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
