# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 09:35
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0058_auto_20171128_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Category icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=120, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_tag',
            field=models.CharField(blank=True, choices=[[None, 'Select tag'], ['SP', 'Simple'], ['CP', 'Configurable'], ['VP', 'Virtual']], default='SP', max_length=120, null=True, verbose_name='Tag'),
        ),
    ]
