# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0059_auto_20171212_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='priority',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_shoes_size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10'], ['11', '11']], default='', max_length=50, null=True, verbose_name='Shoes Size'),
        ),
    ]
