# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0060_auto_20171215_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Rating value'),
        ),
    ]
