# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0062_auto_20171219_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
