# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0063_auto_20171221_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='subs_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_advertisements', to='Juntos.SubCategory'),
        ),
    ]
