# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0065_auto_20171221_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='insured_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Insured Amount'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_depth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product depth'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_height',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='product_height'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product Weight'),
        ),
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_width',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product Width'),
        ),
    ]
