# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0066_auto_20171221_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='valid_upto',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='mode_of_transport',
            field=models.CharField(default='GPS', max_length=50, verbose_name='Mode of Transport'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mode_of_transport',
            field=models.CharField(default='GPS', max_length=50, verbose_name='Mode of Transport'),
        ),
    ]
