# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0067_auto_20180115_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category_flage',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_shoes_size',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_size',
        ),
    ]
