# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 05:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0068_auto_20180122_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmanagement',
            name='product_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['1', 'XS'], ['2', 'S'], ['3', 'M'], ['4', 'L'], ['5', 'XL'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10'], ['11', '11']], max_length=2, verbose_name='Product Size'), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='productsmanagement',
            name='product_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Type'),
        ),
    ]
