# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0070_availablesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=40, verbose_name='Product Type')),
            ],
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_type', to='Juntos.ProductType'),
        ),
    ]
