# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 10:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juntos', '0071_auto_20180122_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmanagement',
            name='product_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, verbose_name='Product Size'), blank=True, null=True, size=None),
        ),
    ]
